/** biome-ignore-all lint/style/useNamingConvention: safe */

/** biome-ignore-all lint/suspicious/noExplicitAny: safe  */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root";
import { Route as BillingRouteImport } from "./app/billing";
import { Route as IndexRouteImport } from "./app/index";

const BillingRoute = BillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/billing": typeof BillingRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/billing": typeof BillingRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/billing": typeof BillingRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/billing";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/billing";
  id: "__root__" | "/" | "/billing";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BillingRoute: typeof BillingRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/billing": {
      id: "/billing";
      path: "/billing";
      fullPath: "/billing";
      preLoaderRoute: typeof BillingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
